config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "photos#index"
  resources :photos
  resources :users

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      post "/login" => "auth#login"
      post "/logout" => "auth#logout"
      resources :photos, only: [:index, :create, :show, :update, :destroy]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :file_location, PhotoImageUploader
  validates_presence_of :title, :date, :description, :file_location
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  before_create :generate_authentication_token

  def generate_authentication_token
    self.authentication_token = Devise.friendly_token
  end

  def self.from_omniauth(auth)
  # Case 1: Find existing user by facebook uid
  user = User.find_by_fb_uid( auth.uid )
  if user
    user.fb_token = auth.credentials.token
    user.save!
    return user
  end

  # Case 2: Find existing user by email
  existing_user = User.find_by_email( auth.info.email )
  if existing_user
    existing_user.fb_uid = auth.uid
    existing_user.fb_token = auth.credentials.token
    existing_user.save!
    return existing_user
  end

  # Case 3: Create new password
  user = User.new
  user.fb_uid = auth.uid
  user.fb_token = auth.credentials.token
  user.email = auth.info.email
  user.password = Devise.friendly_token[0,20]
  user.save!
  return user
end
end

app/controllers/api/v1/auth_controller.rb
class Api::V1::AuthController < ApiController
  before_action :authenticate_user!, only: :logout

  # POST /api/v1/login
  def login
    if params[:email] && params[:password]
      user = User.find_by_email(params[:email])
    end

    if user && user.valid_password?(params[:password])
      render json: {
        message: "Ok",
        auth_token: user.authentication_token,
        user_id: user.id}
    else
      render json: { message:  "Email or Password is wrong" }, status:  401
    end
  end

  # POST /api/v1/logout
  def logout
    # 登入時刷新 token，做為下次登入時比對用，而舊的 token 就失效了
    current_user.generate_authentication_token
    current_user.save!

    render json: { message:  "Ok" }
  end
end

app/controllers/api/v1/photos_controller.rb
class Api::V1::PhotosController < ApiController
  before_action :authenticate_user!, except: :index
  
  def index
    @photos = Photo.all
  end

  def show
    @photo = Photo.find_by(params[:id])
    if !@photo
      render json: {
        message: "Can't find the photo!",
        status: 400
      }
    else
      render "api/v1/photos/show"
    end
  end

  def create
    @photo = Photo.new(photo_params)
    if @photo.save
      render json: {
        message: "Photo created successfully!",
        result: @photo
      }
    else
      render json: {
        errors: @photo.errors
      }
    end
  end

  def update
    @photo = Photo.find_by(id: params[:id])
    if @photo.update(photo_params)
      render json: {
        message: "Photo updated successfully!",
        result: @photo
      }
    else
      render json: {
        errors: @photo.errors
      }
    end
  end

  def destroy
    @photo = Photo.find_by(id: params[:id])
    @photo.destroy
    render json: {
      message: "Photo destroy successfully!"
    }
  end

private
  def photo_params
    params.permit(:title, :date, :description, :file_location)
  end
end

app/controllers/api_controller.rb
class ApiController < ActionController::Base
  before_action :authenticate_user_from_token!

  def authenticate_user_from_token!
    if params[:auth_token].present?
      user = User.find_by_authentication_token(params[:auth_token])
      # sign_in 是 Devise 的方法
      sign_in(user, store: false) if user
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :gender, :age, :region, :phone])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :gender, :region, :age, :phone])
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, :only => [:show, :edit, :update, :destroy]

  def index
    @photos = Photo.all
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    if @photo.save
      redirect_to photos_path
    else
      render :action => :new
    end
  end

  def update
    if @photo.update(photo_params)
      redirect_to photo_path(@photo)
    else
      render :action => :edit
    end
  end

  def destroy
    @photo.destroy

    redirect_to photos_path
  end

  private

  def set_photo
    @photo = Photo.find(params[:id])
  end

  def photo_params
    params.require(:photo).permit(:title, :date, :description, :file_location)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/api/v1/auth_helper.rb
module Api::V1::AuthHelper
end

app/helpers/api/v1/photos_helper.rb
module Api::V1::PhotosHelper
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoAlbum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to "我的家庭相簿", root_path, class: "navbar-brand" %>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li><%= link_to 'All User', users_path %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <% if current_user %>
              <li><p class="navbar-text">Hi, <%= current_user.email %></p></li>
              <li><%= link_to('Log out', destroy_user_session_path, method: :delete) %></li>
              <li><%= link_to('Edit Profile', edit_user_registration_path) %></li>
              <% else %>
              <li><%= link_to('Sign up', new_user_registration_path) %></li>
              <li><%= link_to('Log in', new_user_session_path) %></li>
              <li><%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %></li>
              <% end %>
            </ul>
          </div>

        </div><!-- /.container-fluid -->
      </nav>
      <% if current_user %>
        <p class="pull-right">你的 API Token：<code><%= current_user.authentication_token  %></code></p>
      <% end %>
      <% if flash[:notice] %>
        <div class="alert alert-success" role="alert"><%= notice %></div>
      <% elsif flash[:alert] %>
        <div class="alert alert-danger" role="alert"><%= alert %></div>
      <% end %>
      <%= yield %>
    <div>
  </body>
</html>

app/views/photos/_form.html.erb
<% if @photo.errors.present? %>
  <ul>
    <% @photo.errors.each do |error, message| %>
      <li> <%= "#{error.capitalize}  #{message}" %></li>
    <% end %>
  </ul>
<% end %>

<div class="form container">

  <%= form_for @photo do |f| %>

    <div class="form-group">
      <%= f.label :title, "Title" %>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :date, "Date" %>
      <%= f.text_field :date, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :description, "Description" %>
      <%= f.text_area :description, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :file_location, "File Location" %>
      <%= f.file_field :file_location, class: "form-control" %>
    </div>

    <%= f.submit %>

  <% end %>

</div>

app/views/photos/edit.html.erb
<%= render :partial => "form" %>

app/views/photos/index.html.erb
<table class="table table-striped table-condensed">
  <% @photos.each do |photo| %>
    <tr>
      <td><%= photo.title %></td>
      <td><%= image_tag(photo.file_location)%></td>
      <td><%= link_to 'Show', photo_path(photo) %></td>
      <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
      <td><%= link_to 'Destroy', photo_path(photo), method: :delete, data:{ confirm: "Are you sure?" } %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<%= render :partial => "form" %>

app/views/photos/show.html.erb
<%= @photo.title %>
<%= @photo.date %>
<%= image_tag @photo.file_location.url, size: "140x140", class: "img-thumbnail" %>
<%= simple_format(@photo.description) %>

<%= link_to 'Back to index', photos_path %>

app/views/users/index.html.erb
<h1>All User</h1>

<table class="table">
  <tr>
    <th>Avatar</th>
    <th>Name</th>
    <th>Email</th>
    <th>Gender</th>
    <th>Age</th>
    <th>Region</th>
    <th>Phone</th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= image_tag user.avatar if user.avatar? %></td>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= user.gender %></td>
      <td><%= user.age %></td>
      <td><%= user.region %></td>
      <td><%= user.phone %></td>
    </tr>
  <% end %>
</table>